/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Listos;

import Clases.Conexion;
import Clases.Metodos;
import Clases.SeleccionTabla;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.io.IOException;
import java.net.MalformedURLException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;

/**
 *
 * @author Daniel Eduardo y su intimo amigo Luis
 */


public class Empleado extends javax.swing.JFrame {
    
    Color Morado_Fuerte = new Color(54,33,89);
    Conexion con = new Conexion();
    Connection cn = con.conectar();
    private int fila =0;

    
    public Empleado() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        
        UIManager.put("Alta.selectionBackground", Color.MAGENTA);
        UIManager.put("Alta.opaque", true);
        
        Graficas();
        clientesNuevosxMes();
        IngresosTotales_UltimoMes();
        promedio_edad();

        
        mostrarDatos();
        seleccionarMembresias();
        seleccionarSucursales();
        mostrarTodasM();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        PLinicio = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        PLclientes = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        PLmembresias = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        PLusuario = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        PLsalir = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTextoMorado = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        pnVentanas = new javax.swing.JTabbedPane();
        Inicio = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblNombreA4 = new javax.swing.JLabel();
        lblIngresos = new javax.swing.JLabel();
        lblPromedio = new javax.swing.JLabel();
        lblNombreA6 = new javax.swing.JLabel();
        lblCLN = new javax.swing.JLabel();
        lblNombreA = new javax.swing.JLabel();
        lblNombreA2 = new javax.swing.JLabel();
        lblNombreA3 = new javax.swing.JLabel();
        lblNombreA5 = new javax.swing.JLabel();
        lblNombreE = new javax.swing.JLabel();
        lblEmSucursal = new javax.swing.JLabel();
        lblNombreA1 = new javax.swing.JLabel();
        Clientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaClientes = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtAP = new javax.swing.JTextField();
        txtAM = new javax.swing.JTextField();
        txtCurp = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        cboMembresias = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        cboSucursales = new javax.swing.JComboBox<>();
        btnEditar = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        btnRegistro = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        btnEditar1 = new javax.swing.JLabel();
        Membresias = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaMembresias = new javax.swing.JTable();
        jLabel49 = new javax.swing.JLabel();
        txtBuscarM = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(54, 33, 89));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PLinicio.setBackground(new java.awt.Color(64, 43, 100));
        PLinicio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PLinicioMouseMoved(evt);
            }
        });
        PLinicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PLinicioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PLinicioMouseExited(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebahogar/imagenes/casa-icono-silueta.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Inicio");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PLinicioLayout = new javax.swing.GroupLayout(PLinicio);
        PLinicio.setLayout(PLinicioLayout);
        PLinicioLayout.setHorizontalGroup(
            PLinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PLinicioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PLinicioLayout.setVerticalGroup(
            PLinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PLinicioLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(PLinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        sidePanel.add(PLinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 310, 50));

        PLclientes.setBackground(new java.awt.Color(64, 43, 100));
        PLclientes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PLclientesMouseMoved(evt);
            }
        });
        PLclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PLclientesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PLclientesMouseExited(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebahogar/imagenes/customer-review.png"))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Clientes");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PLclientesLayout = new javax.swing.GroupLayout(PLclientes);
        PLclientes.setLayout(PLclientesLayout);
        PLclientesLayout.setHorizontalGroup(
            PLclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PLclientesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PLclientesLayout.setVerticalGroup(
            PLclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PLclientesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(PLclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        sidePanel.add(PLclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 310, 50));

        PLmembresias.setBackground(new java.awt.Color(64, 43, 100));
        PLmembresias.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PLmembresiasMouseMoved(evt);
            }
        });
        PLmembresias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PLmembresiasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PLmembresiasMouseExited(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebahogar/imagenes/tarjeta-de-membresia.png"))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("Membresias");
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PLmembresiasLayout = new javax.swing.GroupLayout(PLmembresias);
        PLmembresias.setLayout(PLmembresiasLayout);
        PLmembresiasLayout.setHorizontalGroup(
            PLmembresiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PLmembresiasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PLmembresiasLayout.setVerticalGroup(
            PLmembresiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PLmembresiasLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(PLmembresiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        sidePanel.add(PLmembresias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 310, 50));

        PLusuario.setBackground(new java.awt.Color(64, 43, 100));
        PLusuario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PLusuarioMouseMoved(evt);
            }
        });
        PLusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PLusuarioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PLusuarioMouseExited(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebahogar/imagenes/cambiar.png"))); // NOI18N

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("Cambiar de usuario");
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PLusuarioLayout = new javax.swing.GroupLayout(PLusuario);
        PLusuario.setLayout(PLusuarioLayout);
        PLusuarioLayout.setHorizontalGroup(
            PLusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PLusuarioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PLusuarioLayout.setVerticalGroup(
            PLusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PLusuarioLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(PLusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        sidePanel.add(PLusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 340, 50));

        PLsalir.setBackground(new java.awt.Color(64, 43, 100));
        PLsalir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PLsalirMouseMoved(evt);
            }
        });
        PLsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PLsalirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PLsalirMouseExited(evt);
            }
        });

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebahogar/imagenes/cerrar-sesion.png"))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 204, 204));
        jLabel25.setText("Salir");
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PLsalirLayout = new javax.swing.GroupLayout(PLsalir);
        PLsalir.setLayout(PLsalirLayout);
        PLsalirLayout.setHorizontalGroup(
            PLsalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PLsalirLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PLsalirLayout.setVerticalGroup(
            PLsalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PLsalirLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(PLsalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        sidePanel.add(PLsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 340, 50));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Empleado");
        jLabel26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sidePanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 120, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("__________________________");
        jLabel28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sidePanel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 270, 40));

        jPanel1.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 750));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Hecho con ♥");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 110, 30));

        jPanel2.setBackground(new java.awt.Color(122, 72, 221));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextoMorado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTextoMorado.setForeground(new java.awt.Color(255, 255, 255));
        lblTextoMorado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextoMorado.setText("¡Bienvenido de Vuelta!");
        lblTextoMorado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblTextoMorado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, 1520, 40));

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("SANDERS GYM");
        jLabel58.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1520, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 1550, 90));

        pnVentanas.setBackground(new java.awt.Color(255, 255, 255));

        Inicio.setBackground(new java.awt.Color(255, 255, 255));
        Inicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebahogar/imagenes/Modern And Simple GYM Business (2).png"))); // NOI18N
        Inicio.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 530, 260, 90));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        Inicio.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 440, 330));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        Inicio.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 180, 390, 330));

        lblNombreA4.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblNombreA4.setForeground(new java.awt.Color(54, 33, 89));
        lblNombreA4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreA4.setText("______________");
        Inicio.add(lblNombreA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 120, -1));

        lblIngresos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIngresos.setForeground(new java.awt.Color(54, 33, 89));
        lblIngresos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIngresos.setText("jLabel2");
        Inicio.add(lblIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 100, -1));

        lblPromedio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPromedio.setForeground(new java.awt.Color(54, 33, 89));
        lblPromedio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPromedio.setText("jLabel2");
        Inicio.add(lblPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 100, -1));

        lblNombreA6.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblNombreA6.setForeground(new java.awt.Color(54, 33, 89));
        lblNombreA6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreA6.setText("______________");
        Inicio.add(lblNombreA6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 120, -1));

        lblCLN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCLN.setForeground(new java.awt.Color(54, 33, 89));
        lblCLN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCLN.setText("jLabel2");
        Inicio.add(lblCLN, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 110, -1));

        lblNombreA.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblNombreA.setForeground(new java.awt.Color(54, 33, 89));
        lblNombreA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreA.setText("______________");
        Inicio.add(lblNombreA, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 120, -1));

        lblNombreA2.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblNombreA2.setForeground(new java.awt.Color(54, 33, 89));
        lblNombreA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/nuevo_cliente.png"))); // NOI18N
        lblNombreA2.setText(" Clientes nuevos el ultimo mes ");
        Inicio.add(lblNombreA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 330, -1));

        lblNombreA3.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblNombreA3.setForeground(new java.awt.Color(54, 33, 89));
        lblNombreA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/321321.png"))); // NOI18N
        lblNombreA3.setText(" Ingresos Totales el ultimo mes");
        Inicio.add(lblNombreA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 330, -1));

        lblNombreA5.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblNombreA5.setForeground(new java.awt.Color(54, 33, 89));
        lblNombreA5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/grupo-de-edad.png"))); // NOI18N
        lblNombreA5.setText("  Promedio de Edad de los Clientes");
        Inicio.add(lblNombreA5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 350, -1));

        lblNombreE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNombreE.setForeground(new java.awt.Color(54, 33, 89));
        lblNombreE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreE.setText("Nombre(S)");
        Inicio.add(lblNombreE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1550, -1));

        lblEmSucursal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblEmSucursal.setForeground(new java.awt.Color(54, 33, 89));
        lblEmSucursal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmSucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ubicacion (1).png"))); // NOI18N
        lblEmSucursal.setText("     Correo Electronico");
        Inicio.add(lblEmSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1550, 70));

        lblNombreA1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNombreA1.setForeground(new java.awt.Color(54, 33, 89));
        lblNombreA1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreA1.setText("¡Construye tu mejor versión!");
        Inicio.add(lblNombreA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 1500, -1));

        pnVentanas.addTab("tab1", Inicio);

        Clientes.setBackground(new java.awt.Color(255, 255, 255));
        Clientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        TablaClientes.setAutoCreateRowSorter(true);
        TablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre(s)", "Apellido Paterno", "Apellido Materno", "Direccion", "Telefono", "Fecha de Inscripcion", "Fecha de Baja", "Correo Electronico", "Membresia", "Title 11"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaClientes.setGridColor(new java.awt.Color(255, 255, 255));
        TablaClientes.setSelectionBackground(new java.awt.Color(122, 72, 221));
        TablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaClientes);

        Clientes.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 1190, 260));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebahogar/imagenes/cliente2.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 70, 80));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(54, 33, 89));
        jLabel6.setText("Cliente");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 60, 30));

        txtCorreo.setForeground(new java.awt.Color(204, 204, 204));
        txtCorreo.setText("Correo Electronico");
        txtCorreo.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtCorreo.setSelectionColor(new java.awt.Color(122, 72, 221));
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCorreoMouseClicked(evt);
            }
        });
        jPanel4.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 190, 30));

        txtNombre.setForeground(new java.awt.Color(204, 204, 204));
        txtNombre.setText("Nombre(s)");
        txtNombre.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtNombre.setSelectionColor(new java.awt.Color(122, 72, 221));
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel4.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 190, 30));

        txtAP.setForeground(new java.awt.Color(204, 204, 204));
        txtAP.setText("Apellido Paterno");
        txtAP.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtAP.setSelectionColor(new java.awt.Color(122, 72, 221));
        txtAP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAPMouseClicked(evt);
            }
        });
        jPanel4.add(txtAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 190, 30));

        txtAM.setForeground(new java.awt.Color(204, 204, 204));
        txtAM.setText("Apellido Materno");
        txtAM.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtAM.setSelectionColor(new java.awt.Color(122, 72, 221));
        txtAM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAMMouseClicked(evt);
            }
        });
        jPanel4.add(txtAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 190, 30));

        txtCurp.setForeground(new java.awt.Color(204, 204, 204));
        txtCurp.setText("CURP");
        txtCurp.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtCurp.setSelectionColor(new java.awt.Color(122, 72, 221));
        txtCurp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCurpMouseClicked(evt);
            }
        });
        jPanel4.add(txtCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 190, 30));

        txtTelefono.setForeground(new java.awt.Color(204, 204, 204));
        txtTelefono.setText("Telefono");
        txtTelefono.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtTelefono.setSelectionColor(new java.awt.Color(122, 72, 221));
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTelefonoMouseClicked(evt);
            }
        });
        jPanel4.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 190, 30));

        txtDireccion.setForeground(new java.awt.Color(204, 204, 204));
        txtDireccion.setText("Direccion");
        txtDireccion.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtDireccion.setSelectionColor(new java.awt.Color(122, 72, 221));
        txtDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDireccionMouseClicked(evt);
            }
        });
        jPanel4.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 190, 30));

        txtEdad.setForeground(new java.awt.Color(204, 204, 204));
        txtEdad.setText("Edad");
        txtEdad.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtEdad.setSelectionColor(new java.awt.Color(122, 72, 221));
        txtEdad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEdadMouseClicked(evt);
            }
        });
        jPanel4.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 190, 30));

        jLabel30.setText("Membresias");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        jPanel4.add(cboMembresias, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 150, 30));

        jLabel34.setText("Sucursales");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        jPanel4.add(cboSucursales, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 150, 30));

        Clientes.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -20, 240, 630));

        btnEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(54, 33, 89));
        btnEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editar.png"))); // NOI18N
        btnEditar.setText("  Editar");
        btnEditar.setToolTipText("");
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.setOpaque(true);
        btnEditar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEditarMouseMoved(evt);
            }
        });
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
        });
        Clientes.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, 170, 50));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebahogar/imagenes/Modern And Simple GYM Business (2).png"))); // NOI18N
        Clientes.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 530, 260, 90));

        btnRegistro.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistro.setForeground(new java.awt.Color(54, 33, 89));
        btnRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/registro (1).png"))); // NOI18N
        btnRegistro.setText("  Nuevo Registro");
        btnRegistro.setToolTipText("");
        btnRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistro.setOpaque(true);
        btnRegistro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnRegistroMouseMoved(evt);
            }
        });
        btnRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistroMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistroMouseExited(evt);
            }
        });
        Clientes.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 210, 50));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebahogar/imagenes/lupa.png"))); // NOI18N
        Clientes.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, -1));

        txtBuscar.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtBuscar.setSelectionColor(new java.awt.Color(122, 72, 221));
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        Clientes.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 200, -1));

        jLabel55.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(54, 33, 89));
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("Buscar por Nombre");
        Clientes.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 200, -1));

        btnEditar1.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditar1.setForeground(new java.awt.Color(54, 33, 89));
        btnEditar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEditar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/enviar-datos.png"))); // NOI18N
        btnEditar1.setText("  Crear y Enviar PDF");
        btnEditar1.setToolTipText("");
        btnEditar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar1.setOpaque(true);
        btnEditar1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEditar1MouseMoved(evt);
            }
        });
        btnEditar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditar1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditar1MouseExited(evt);
            }
        });
        Clientes.add(btnEditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 440, 250, 50));

        pnVentanas.addTab("tab3", Clientes);

        Membresias.setBackground(new java.awt.Color(255, 255, 255));
        Membresias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebahogar/imagenes/Modern And Simple GYM Business (2).png"))); // NOI18N
        Membresias.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 530, 260, 90));

        jScrollPane4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        TablaMembresias.setAutoCreateRowSorter(true);
        TablaMembresias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(122, 72, 221)));
        TablaMembresias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre(s)", "Apellido Paterno", "Apellido Materno", "Direccion", "Telefono", "Fecha de Inscripcion", "Fecha de Baja", "Correo Electronico", "Membresia", "Title 11"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaMembresias.setGridColor(new java.awt.Color(255, 255, 255));
        TablaMembresias.setSelectionBackground(new java.awt.Color(122, 72, 221));
        TablaMembresias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMembresiasMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TablaMembresias);

        Membresias.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 1490, 420));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebahogar/imagenes/lupa.png"))); // NOI18N
        Membresias.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, -1, -1));

        txtBuscarM.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtBuscarM.setSelectionColor(new java.awt.Color(122, 72, 221));
        txtBuscarM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarMKeyReleased(evt);
            }
        });
        Membresias.add(txtBuscarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 200, -1));

        jLabel56.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(54, 33, 89));
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("Buscar por Nombre");
        Membresias.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 75, 200, 30));

        pnVentanas.addTab("tab4", Membresias);

        jPanel1.add(pnVentanas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 1550, 650));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1860, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PLinicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLinicioMouseClicked
        // TODO add your handling code here:
        pnVentanas.setSelectedIndex(0);
        lblTextoMorado.setText("Inicio");
        Graficas();
        clientesNuevosxMes();
        IngresosTotales_UltimoMes();
        promedio_edad();
    }//GEN-LAST:event_PLinicioMouseClicked

    private void PLinicioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLinicioMouseMoved
        // TODO add your handling code here:
        PLinicio.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_PLinicioMouseMoved

    private void PLinicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLinicioMouseExited
        // TODO add your handling code here:
        PLinicio.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_PLinicioMouseExited

    private void PLclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLclientesMouseClicked
        // TODO add your handling code here:
        pnVentanas.setSelectedIndex(1);
        lblTextoMorado.setText("Gestion de Clientes");
    }//GEN-LAST:event_PLclientesMouseClicked

    private void PLclientesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLclientesMouseMoved
        // TODO add your handling code here:
        PLclientes.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_PLclientesMouseMoved

    private void PLclientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLclientesMouseExited
        // TODO add your handling code here:
        PLclientes.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_PLclientesMouseExited

    private void PLmembresiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLmembresiasMouseClicked
        // TODO add your handling code here:
        pnVentanas.setSelectedIndex(2);
    }//GEN-LAST:event_PLmembresiasMouseClicked

    private void PLmembresiasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLmembresiasMouseMoved
        // TODO add your handling code here:
        PLmembresias.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_PLmembresiasMouseMoved

    private void PLmembresiasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLmembresiasMouseExited
        // TODO add your handling code here:
        PLmembresias.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_PLmembresiasMouseExited

    private void PLusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLusuarioMouseClicked
        // TODO add your handling code here:
        this.dispose();
        login log = new login();
        log.setVisible(true);
        
 
    }//GEN-LAST:event_PLusuarioMouseClicked

    private void PLusuarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLusuarioMouseMoved
        // TODO add your handling code here:
        PLusuario.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_PLusuarioMouseMoved

    private void PLusuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLusuarioMouseExited
        // TODO add your handling code here:
         PLusuario.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_PLusuarioMouseExited

    private void PLsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLsalirMouseClicked
        // TODO add your handling code here:
         int response = JOptionPane.showConfirmDialog(Empleado.this,
                    "¿Seguro que deseas cerrar el programa?",
                    "Confirmar Cierre",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE
                );

                // Si el usuario selecciona "Sí", cerrar el programa
                if (response == JOptionPane.YES_OPTION) {
                   this.dispose();
                }
    }//GEN-LAST:event_PLsalirMouseClicked

    private void PLsalirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLsalirMouseMoved
        // TODO add your handling code here:
        PLsalir.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_PLsalirMouseMoved

    private void PLsalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLsalirMouseExited
        // TODO add your handling code here:
        PLsalir.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_PLsalirMouseExited

    private void TablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaClientesMouseClicked
        // TODO add your handling code here:
        fila = TablaClientes.getSelectedRow();

        int id = Integer.parseInt((String) TablaClientes.getValueAt(fila, 0)); 

        PreparedStatement ps = null;
        ResultSet rs = null;

        String consulta = "select edad,telefono,curp from persona where id_persona = ?";

        try {

            cn = con.conectar();
            ps = cn.prepareStatement(consulta);
            ps.setInt(1, id);
            rs = ps.executeQuery();
            if (rs.next()) {
                String Edad = rs.getString(1);
                String Telefono = rs.getString(2);
                String Curp = rs.getString(3);

                txtEdad.setText(Edad);
                txtEdad.setForeground(Morado_Fuerte);

                txtTelefono.setText(Telefono);
                txtTelefono.setForeground(Morado_Fuerte);

                txtCurp.setText(Curp);
                txtCurp.setForeground(Morado_Fuerte);
            }

        }
        catch (Exception e) {
        }

        //System.out.println(id);

        txtNombre.setText(TablaClientes.getValueAt(fila, 1).toString()       );
        txtNombre.setForeground(Morado_Fuerte);

        txtAP.setText(TablaClientes.getValueAt(fila, 2).toString());
        txtAP.setForeground(Morado_Fuerte);

        txtAM.setText(TablaClientes.getValueAt(fila, 3).toString());
        txtAM.setForeground(Morado_Fuerte);

        txtDireccion.setText(TablaClientes.getValueAt(fila, 4).toString());
        txtDireccion.setForeground(Morado_Fuerte);

        txtCorreo.setText(TablaClientes.getValueAt(fila, 5).toString());
        txtCorreo.setForeground(Morado_Fuerte);

        cboMembresias.setSelectedItem(TablaClientes.getValueAt(fila, 8).toString());
        cboSucursales.setSelectedItem(TablaClientes.getValueAt(fila, 9).toString());

    }//GEN-LAST:event_TablaClientesMouseClicked

    private void txtCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMouseClicked
        // TODO add your handling code here:
        String aux = "Correo Electronico";

        if (txtCorreo.getText().isEmpty() || txtCorreo.getText().equals(aux)){
            txtCorreo.setForeground(new Color(54,33,89));
            txtCorreo.setText("");
        }

    }//GEN-LAST:event_txtCorreoMouseClicked

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        // TODO add your handling code here:
        String aux = "Nombre(s)";
        if (txtNombre.getText().isEmpty() || txtNombre.getText().equals(aux)){
             txtNombre.setForeground(new Color(54,33,89));
            txtNombre.setText("");
        }
    }//GEN-LAST:event_txtNombreMouseClicked

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtAPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAPMouseClicked
        // TODO add your handling code here:
        String aux = "Apellido Paterno";
        if (txtAP.getText().isEmpty() || txtAP.getText().equals(aux)){
            txtAP.setForeground(new Color(54,33,89));
            txtAP.setText("");
        }
    }//GEN-LAST:event_txtAPMouseClicked

    private void txtAMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAMMouseClicked
        // TODO add your handling code here:
        String aux = "Apellido Materno";
        if (txtAM.getText().isEmpty() || txtAM.getText().equals(aux)){
            txtAM.setForeground(new Color(54,33,89));
            txtAM.setText("");
        }
    }//GEN-LAST:event_txtAMMouseClicked

    private void txtCurpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCurpMouseClicked
        // TODO add your handling code here:
        String aux = "CURP";
        if (txtCurp.getText().isEmpty() || txtCurp.getText().equals(aux)){
            txtCurp.setForeground(new Color(54,33,89));
            txtCurp.setText("");
        }
    }//GEN-LAST:event_txtCurpMouseClicked

    private void txtTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMouseClicked
        // TODO add your handling code here:
        String aux = "Telefono";
        if (txtTelefono.getText().isEmpty() || txtTelefono.getText().equals(aux)){
            txtTelefono.setForeground(new Color(54,33,89));
            txtTelefono.setText("");
        }
    }//GEN-LAST:event_txtTelefonoMouseClicked

    private void txtDireccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDireccionMouseClicked
        // TODO add your handling code here:
        String aux = "Direccion";
        if (txtDireccion.getText().isEmpty() || txtDireccion.getText().equals(aux)){
            txtDireccion.setForeground(new Color(54,33,89));
            txtDireccion.setText("");
        }
    }//GEN-LAST:event_txtDireccionMouseClicked

    private void txtEdadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEdadMouseClicked
        // TODO add your handling code here:
        String aux = "Edad";
        if (txtEdad.getText().isEmpty() || txtEdad.getText().equals(aux)){
            txtEdad.setForeground(new Color(54,33,89));
            txtEdad.setText("");
        }
    }//GEN-LAST:event_txtEdadMouseClicked

    private void btnEditarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseMoved
        // TODO add your handling code here:
        btnEditar.setBackground(Color.white);
    }//GEN-LAST:event_btnEditarMouseMoved

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        String Nombre = txtNombre.getText().trim();
        String A_Paterno = txtAP.getText().trim();
        String A_Materno = txtAM.getText().trim();
        String CURP = txtCurp.getText().trim();
        String Direccion = txtDireccion.getText().trim();
        String Telefono = txtTelefono.getText().trim();
        String edadStr = txtEdad.getText().trim();
        String correo = txtCorreo.getText().trim();

        String Membresia = (String) cboMembresias.getSelectedItem();
        String Sucursal = (String) cboSucursales.getSelectedItem();

        fila = TablaClientes.getSelectedRow();
        int id = Integer.parseInt((String) TablaClientes.getValueAt(fila, 0)); ///////////////////---------------------------------IDPERsona
        
        // Validar que el teléfono contenga solo números y tenga entre 7 y 10 caracteres
        if (!Telefono.matches("\\d{7,10}")) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese un número de teléfono válido (7-10 dígitos).", "Teléfono inválido", JOptionPane.ERROR_MESSAGE);
        return;
        }
        // Validar la CURP
        if (!CURP.matches("^[A-Z]{4}\\d{6}[HM][A-Z]{5}[A-Z0-9]{2}$")) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese una CURP válida.", "CURP inválida", JOptionPane.ERROR_MESSAGE);
        return;
        }
        
        // Validar el correo electrónico con dominios específicos
        if (!correo.matches("^[\\w.-]+@(gmail\\.com|hotmail\\.com|yahoo\\.com|outlook\\.com)$")) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese un correo electrónico válido con un dominio permitido (gmail.com, hotmail.com, yahoo.com, outlook.com).", "Correo inválido", JOptionPane.ERROR_MESSAGE);
        return;
        }

        //----------------------------------------------------------------------------------------------------Selecciona los datos del registro
        try {
            int Edad = Integer.parseInt(edadStr);
            Clases.Metodos objetoRegistro = new Clases.Metodos();

            if (id != -1) {
                // Llamar al método para guardar el correo y la fecha de inscripción del cliente
                objetoRegistro.ActualizarCliente(id, Nombre, A_Paterno, A_Materno, CURP, Direccion, Telefono, Edad, correo);

                objetoRegistro.ActualizarMembresia(Membresia, id, Sucursal);
                JOptionPane.showMessageDialog(this, "Cliente modficado exitosamente.");

                LimpiarCampos();

            } else {
                JOptionPane.showMessageDialog(this, "Error al obtener el ID de la persona.", "Error", JOptionPane.ERROR_MESSAGE);
            }

            try {
                objetoRegistro.crearPDF(id);
            } catch (MalformedURLException ex) {
                Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        catch (Exception e) { // General catch for unexpected exceptions
            JOptionPane.showMessageDialog(this, "Error al guardar los datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

        mostrarDatos();
        mostrarTodasM();
        

        Clases.Metodos objetoRegistro = new Clases.Metodos();

        try {
            objetoRegistro.crearPDF_EC(id);
        } catch (MalformedURLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseExited
        // TODO add your handling code here:
        btnEditar.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnEditarMouseExited

    private void btnRegistroMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroMouseMoved

    private void btnRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroMouseClicked
        // TODO add your handling code here:
        String Nombre = txtNombre.getText().trim();
        String A_Paterno = txtAP.getText().trim();
        String A_Materno = txtAM.getText().trim();
        String CURP = txtCurp.getText().trim();
        String Direccion = txtDireccion.getText().trim();
        String Telefono = txtTelefono.getText().trim();
        String edadStr = txtEdad.getText().trim();
        String correo = txtCorreo.getText().trim();
        java.util.Date fechaInscripcion = new java.util.Date(); // Fecha de inscripción actual

        String Membresia = (String) cboMembresias.getSelectedItem();
        String Sucursal = (String) cboSucursales.getSelectedItem();

        // Verificar que todos los campos estén llenos
        if (Nombre.isEmpty() || A_Paterno.isEmpty() || A_Materno.isEmpty() || CURP.isEmpty() || Direccion.isEmpty() || Telefono.isEmpty() || edadStr.isEmpty() || correo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, llene todos los campos.", "Campos vacíos", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Validar que el teléfono contenga solo números y tenga entre 7 y 10 caracteres
        if (!Telefono.matches("\\d{7,10}")) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese un número de teléfono válido (7-10 dígitos).", "Teléfono inválido", JOptionPane.ERROR_MESSAGE);
        return;
        }
        
        // Validar la CURP
        if (!CURP.matches("^[A-Z]{4}\\d{6}[HM][A-Z]{5}[A-Z0-9]{2}$")) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese una CURP válida.", "CURP inválida", JOptionPane.ERROR_MESSAGE);
        return;
        }
        
        // Validar el correo electrónico con dominios específicos
        if (!correo.matches("^[\\w.-]+@(gmail\\.com|hotmail\\.com|yahoo\\.com|outlook\\.com)$")) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese un correo electrónico válido con un dominio permitido (gmail.com, hotmail.com, yahoo.com, outlook.com).", "Correo inválido", JOptionPane.ERROR_MESSAGE);
        return;
        }

        try {
            // Convertir Edad a entero
            int Edad = Integer.parseInt(edadStr);

            Clases.Metodos objetoRegistro = new Clases.Metodos();
            objetoRegistro.GuardarDatosPersona(Nombre, A_Paterno, A_Materno, CURP, Direccion, Telefono, Edad);
            int id_cliente = objetoRegistro.obtenerUltimoIdPersona();

            if (id_cliente != -1) {

                objetoRegistro.GuardarCorreoYFechaCliente(id_cliente, correo, new java.sql.Date(fechaInscripcion.getTime()));

                JOptionPane.showMessageDialog(this, "Cliente registrado exitosamente.");

                LimpiarCampos();

            } else {
                JOptionPane.showMessageDialog(this, "Error al obtener el ID de la persona.", "Error", JOptionPane.ERROR_MESSAGE);
            }

            objetoRegistro.setMembresia(Membresia, id_cliente);
            int id_m = objetoRegistro.obtenerUltimoIdMembresia();

            objetoRegistro.setGimnasio(Sucursal, id_m, new java.sql.Date(fechaInscripcion.getTime()));

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese una edad válida.", "Edad inválida", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) { // General catch for unexpected exceptions
            JOptionPane.showMessageDialog(this, "Error al guardar los datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

        mostrarDatos();
        mostrarTodasM();
        
        

        Clases.Metodos objetoRegistro = new Clases.Metodos();

        int id_cliente = objetoRegistro.obtenerUltimoIdPersona();

        try {
            objetoRegistro.crearPDF(id_cliente);
        } catch (MalformedURLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnRegistroMouseClicked

    private void btnRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroMouseExited

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        mostrarDatos();

    }//GEN-LAST:event_txtBuscarKeyReleased

    private void TablaMembresiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMembresiasMouseClicked
    }//GEN-LAST:event_TablaMembresiasMouseClicked

    private void txtBuscarMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarMKeyReleased
        mostrarTodasM();
    }//GEN-LAST:event_txtBuscarMKeyReleased

    private void btnEditar1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditar1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditar1MouseMoved

    private void btnEditar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditar1MouseClicked
        Clases.Metodos objetoRegistro = new Clases.Metodos();

        fila = TablaClientes.getSelectedRow();
        int id = Integer.parseInt((String) TablaClientes.getValueAt(fila, 0)); ///////////////////---------------------------------IDPERsona
        if (id != -1) {
        } else {
            JOptionPane.showMessageDialog(this, "Error al obtener el ID de la persona.", "Error", JOptionPane.ERROR_MESSAGE);

        }

        try {
            objetoRegistro.crearPDF(id);
        } catch (MalformedURLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditar1MouseClicked

    private void btnEditar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditar1MouseExited

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Empleado().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Empleado.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Clientes;
    private javax.swing.JPanel Inicio;
    private javax.swing.JPanel Membresias;
    private javax.swing.JPanel PLclientes;
    private javax.swing.JPanel PLinicio;
    private javax.swing.JPanel PLmembresias;
    private javax.swing.JPanel PLsalir;
    private javax.swing.JPanel PLusuario;
    public javax.swing.JTable TablaClientes;
    public javax.swing.JTable TablaMembresias;
    public javax.swing.JLabel btnEditar;
    public javax.swing.JLabel btnEditar1;
    public javax.swing.JLabel btnRegistro;
    public javax.swing.JComboBox<String> cboMembresias;
    public javax.swing.JComboBox<String> cboSucursales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblCLN;
    private javax.swing.JLabel lblEmSucursal;
    private javax.swing.JLabel lblIngresos;
    private javax.swing.JLabel lblNombreA;
    private javax.swing.JLabel lblNombreA1;
    private javax.swing.JLabel lblNombreA2;
    private javax.swing.JLabel lblNombreA3;
    private javax.swing.JLabel lblNombreA4;
    private javax.swing.JLabel lblNombreA5;
    private javax.swing.JLabel lblNombreA6;
    private javax.swing.JLabel lblNombreE;
    private javax.swing.JLabel lblPromedio;
    private javax.swing.JLabel lblTextoMorado;
    private javax.swing.JTabbedPane pnVentanas;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTextField txtAM;
    private javax.swing.JTextField txtAP;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtBuscarM;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCurp;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
    
    public void setUserDataE(String nombre, String aPaterno, String aMaterno, String direccion, String telefono, int edad, String correoEmpleado) {
         lblNombreE.setText(nombre + " " + aPaterno + " " + aMaterno);
        
    }
    public void setSucursal(String nombre){
    
        lblEmSucursal.setText("  "+nombre);
    
    }
    
    private void mostrarDatos() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre(s)");
        modelo.addColumn("Apellido Paterno");
        modelo.addColumn("Apellido Materno");
        modelo.addColumn("Direccion");
        modelo.addColumn("Correo Electronico");
        modelo.addColumn("Fecha Inscripcion");
        modelo.addColumn("Fecha Baja");
        modelo.addColumn("Membresia");
        modelo.addColumn("Sucursal");

        TablaClientes.setModel(modelo);
        
        TableColumnModel columnModel = TablaClientes.getColumnModel();
        TableColumn idColumn = columnModel.getColumn(0);
        idColumn.setPreferredWidth(10);

        String consulta = "SELECT p.id_persona, p.Nombre, p.A_Paterno, p.A_Materno, p.Direccion, c.correo_cliente, "
                + "c.fecha_inscripcion, c.fecha_baja, m.nombre AS nombre_membresia, g.nombre AS nombre_gimnasio "
                + "FROM persona p JOIN cliente c ON p.id_persona = c.id_cliente "
                + "JOIN membresia m ON c.id_cliente = m.cliente_m "
                + "JOIN gimnasio g ON m.id_membresia = g.membresia_g";

        String aux_final = consulta + " WHERE p.Nombre LIKE ? OR p.A_Paterno LIKE ? OR p.A_Materno LIKE ?";

        try {
            ResultSet rs;
            if (txtBuscar.getText().isEmpty()) {
                Statement st = cn.createStatement();
                rs = st.executeQuery(consulta);
            } else {
                PreparedStatement pst = cn.prepareStatement(aux_final);
                String searchText = "%" + txtBuscar.getText() + "%";
                pst.setString(1, searchText);
                pst.setString(2, searchText);
                pst.setString(3, searchText);
                rs = pst.executeQuery();
            }

            while (rs.next()) {
                String[] data = new String[10];
                data[0] = rs.getString("id_persona");
                data[1] = rs.getString("Nombre");
                data[2] = rs.getString("A_Paterno");
                data[3] = rs.getString("A_Materno");
                data[4] = rs.getString("Direccion");
                data[5] = rs.getString("correo_cliente");
                data[6] = rs.getString("fecha_inscripcion");
                data[7] = rs.getString("fecha_baja");
                data[8] = rs.getString("nombre_membresia");
                data[9] = rs.getString("nombre_gimnasio");

                modelo.addRow(data);
            }

            rs.close();
        } catch (SQLException e) {
            System.out.println("Error al mostrar los datos de la BD: " + e.getMessage());
        }

        SeleccionTabla renderer = new SeleccionTabla();
        TablaClientes.getColumnModel().getColumn(7).setCellRenderer(renderer);
        
        
    }
    private void LimpiarCampos() {
        txtNombre.setText("Nombre(s)");
        txtNombre.setForeground(new Color(204,204,204));
        
        txtAP.setText("Apellido Paterno");
        txtAP.setForeground(new Color(204,204,204));
        
        txtAM.setText("Apellido Materno");
        txtAM.setForeground(new Color(204,204,204));
        
        txtCurp.setText("CURP");
        txtCurp.setForeground(new Color(204,204,204));
        
        txtTelefono.setText("Telefono");
        txtTelefono.setForeground(new Color(204,204,204));
        
        txtDireccion.setText("Direccion");
        txtDireccion.setForeground(new Color(204,204,204));
        
        txtCorreo.setText("Correo Electronico");
        txtCorreo.setForeground(new Color(204,204,204));
        
        txtEdad.setText("Edad");
        txtEdad.setForeground(new Color(204,204,204));
        
    }
    
    private void mostrarTodasM() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("N°");
        modelo.addColumn("Nombre");
        modelo.addColumn("Precio");
        modelo.addColumn("Descripción");
        modelo.addColumn("Clientes asociados a la membresía");

        TablaMembresias.setModel(modelo);

        TableColumnModel columnModel = TablaMembresias.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(5);

        String consultaBase = "SELECT m.nombre, m.precio, m.descripcion, "
                + "COUNT(c.id_cliente) AS cantidad "
                + "FROM Membresia m "
                + "LEFT JOIN Cliente c ON m.cliente_m = c.id_cliente AND c.fecha_baja IS NULL";
        String consulta = consultaBase;
        boolean tieneFiltro = !txtBuscarM.getText().isEmpty();

        if (tieneFiltro) {
            consulta += " WHERE m.nombre LIKE ? GROUP BY m.nombre, m.precio, m.descripcion";
        } else {
            consulta += " GROUP BY m.nombre, m.precio, m.descripcion";
        }

        try (Connection cn = new Conexion().conectar(); PreparedStatement pst = cn.prepareStatement(consulta)) {

            ResultSet rs;

            if (tieneFiltro) {
                String searchText = "%" + txtBuscarM.getText() + "%";
                pst.setString(1, searchText);
                rs = pst.executeQuery();
            } else {
                rs = pst.executeQuery();
            }

            int c = 1;

            while (rs.next()) {
                String[] data = new String[5];
                data[0] = String.valueOf(c++);
                data[1] = rs.getString("nombre");
                data[2] = rs.getString("precio");
                data[3] = rs.getString("descripcion");
                data[4] = String.valueOf(rs.getInt("cantidad"));
                modelo.addRow(data);
            }

            rs.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar los datos de la BD: " + e.getMessage());
        }
    }
    
    private void seleccionarMembresias(){
    
        String consulta = "select distinct nombre from membresia" ;
        Statement st;

        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(consulta);
            while (rs.next()) {                
                String a= rs.getString( "nombre" );
                cboMembresias.addItem(a);
            }
        } 
        catch (Exception e) {
        }
         
    }
    
    private void Graficas(){
    
        Metodos metodos = new Metodos();
        JFreeChart graficoPastel = metodos.generarGraficoPastel();
        ChartPanel chartPanel = new ChartPanel(graficoPastel);
        chartPanel.setPreferredSize(new Dimension(440, 330)); 
        chartPanel.setVisible(true);
        
        
        jPanel3.removeAll(); 
        jPanel3.setLayout(new BorderLayout()); 
        jPanel3.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0, 0)));
        jPanel3.add(chartPanel, BorderLayout.CENTER);
        jPanel3.revalidate(); 
        jPanel3.repaint(); 
        

        JFreeChart GraficaBarras = metodos.generarGraficoBarras();

        
        ChartPanel chartPanel1 = new ChartPanel(GraficaBarras);

        // Establecer un tamaño adecuado para el panel
        chartPanel1.setPreferredSize(new Dimension(440, 330)); // Por ejemplo, 800x600 píxeles

        // Asegurarse de que el panel sea visible
        chartPanel1.setVisible(true);

        // Suponiendo que "jPanel11" es el nombre de tu panel en la interfaz
        jPanel6.removeAll(); // Limpiar el panel si hay otros gráficos
        jPanel6.setLayout(new BorderLayout()); // Asegúrate de que usa BorderLayout

        jPanel6.add(chartPanel1, BorderLayout.CENTER);
        jPanel6.revalidate(); // Validar el panel para que se muestre el gráfico
        jPanel6.repaint();
    
    }
    
    private void clientesNuevosxMes(){
    
        String consulta = "SELECT COUNT(*) AS cantidad_de_clientes FROM cliente WHERE MONTH(fecha_inscripcion) = MONTH(CURDATE()) AND YEAR(fecha_inscripcion) = YEAR(CURDATE()) AND fecha_baja IS NULL";
        Statement st;

        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(consulta);
            if (rs.next()) {                
                String a= String.valueOf(rs.getInt("cantidad_de_clientes"));
                lblCLN.setText(a);
            }
        } 
        catch (SQLException e) {
        }
         
    }
    
    private void IngresosTotales_UltimoMes(){
        
        String consulta = "SELECT SUM(m.precio) AS total_precio_membresias FROM cliente c JOIN membresia m ON c.id_cliente = m.cliente_m WHERE MONTH(c.fecha_inscripcion) = MONTH(CURDATE())" 
                            + "AND YEAR(c.fecha_inscripcion) = YEAR(CURDATE()) AND c.fecha_baja IS NULL" ;
        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(consulta);
            if (rs.next()) {                
                String a= String.valueOf(rs.getInt("total_precio_membresias"));
                lblIngresos.setText("$"+a);
            }
        } 
        catch (SQLException e) {
        }
    }
    
    private void promedio_edad(){
        
        String consulta = "SELECT AVG(p.Edad) AS promedio_edad FROM Persona p JOIN Cliente c ON p.id_persona = c.id_cliente WHERE c.fecha_baja IS NULL";
                
        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(consulta);
            if (rs.next()) {                
                String a= String.valueOf(rs.getDouble("promedio_edad"));
                lblPromedio.setText(a);
            }
        } 
        catch (SQLException e) {
        }
    
    }
    
    
    
    private void seleccionarSucursales() throws SQLException {
        String consulta = "SELECT DISTINCT nombre, fecha_cierre FROM gimnasio";
        
        try (Statement st = cn.createStatement(); 
             ResultSet rs = st.executeQuery(consulta)) {
            
            while (rs.next()) {
                String nombre = rs.getString("nombre");
                Date fechaCierre = rs.getDate("fecha_cierre");

                if (fechaCierre == null) {
                    cboSucursales.addItem(nombre);
                    
                }
            }
        } 
}
}
